name: lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  addon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with: { persist-credentials: false }
      - name: Home Assistant add-on linter
        uses: frenck/action-addon-linter@b9cfd1bc62ba60d2c4fc96317b5f7ada5923f4a7 # v2.21.1
        with:
          path: "./airlock-connector"
